### ISSUE TITLE
Gif duration bugs

### ISSUE THREAD

**Issue by seth-wat** [aquent-it-solutions/Reddit-Humor-v2#16]
Currently due to a typo noticed by @forrestblade in the `gif-me-info` package we are using, we cannot parse gif duration.
*  The code is small. The `index.js` file in the module can just be brought into `utils/gifDuration.js` and fixed
* The promise being returned currently from `gifDuration` can be resolved and just the duration returned

**Comment by theschubinator** [comment]
was just gonna asked if anyone has raised this issue yet...good job Seth..LOL
