### ISSUE TITLE
Ensure that GIFS work properly

### ISSUE THREAD

**Issue by forrestblade** [aquent-it-solutions/Reddit-Humor-v2#31]
I don't believe anyone has manually fed the application a GIF to ensure we haven't made any mistakes on that end.

**Comment by priyankacheema** [comment]
Hello Forrest,

I just checked that GIFS are working just fine. I changed the URLs of images to gifs in response.json file and was trying to fetch data from there instead of the API. And the application was working just fine with those GIFS there. Is there anything else to be tested for this issue?

**Comment by forrestblade** [comment]
LGTM
